/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProjetistasRouteImport } from './routes/authenticated/projetistas'
import { Route as AuthenticatedProjectsRouteImport } from './routes/authenticated/projects'
import { Route as AuthenticatedFluxoDeAprovacaoRouteImport } from './routes/authenticated/fluxo-de-aprovacao'
import { Route as AuthenticatedEquipeRouteImport } from './routes/authenticated/equipe'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/authenticated/documents'
import { Route as AuthenticatedDisciplinesRouteImport } from './routes/authenticated/disciplines'
import { Route as AuthenticatedDashboardRouteImport } from './routes/authenticated/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetistasRoute =
  AuthenticatedProjetistasRouteImport.update({
    id: '/projetistas',
    path: '/projetistas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluxoDeAprovacaoRoute =
  AuthenticatedFluxoDeAprovacaoRouteImport.update({
    id: '/fluxo-de-aprovacao',
    path: '/fluxo-de-aprovacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisciplinesRoute =
  AuthenticatedDisciplinesRouteImport.update({
    id: '/disciplines',
    path: '/disciplines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
  id:
    | '__root__'
    | '/'
    | '/authenticated'
    | '/auth'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/projetistas': {
      id: '/authenticated/projetistas'
      path: '/projetistas'
      fullPath: '/authenticated/projetistas'
      preLoaderRoute: typeof AuthenticatedProjetistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/projects': {
      id: '/authenticated/projects'
      path: '/projects'
      fullPath: '/authenticated/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/fluxo-de-aprovacao': {
      id: '/authenticated/fluxo-de-aprovacao'
      path: '/fluxo-de-aprovacao'
      fullPath: '/authenticated/fluxo-de-aprovacao'
      preLoaderRoute: typeof AuthenticatedFluxoDeAprovacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/equipe': {
      id: '/authenticated/equipe'
      path: '/equipe'
      fullPath: '/authenticated/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/documents': {
      id: '/authenticated/documents'
      path: '/documents'
      fullPath: '/authenticated/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/disciplines': {
      id: '/authenticated/disciplines'
      path: '/disciplines'
      fullPath: '/authenticated/disciplines'
      preLoaderRoute: typeof AuthenticatedDisciplinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/dashboard': {
      id: '/authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/authenticated/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisciplinesRoute: typeof AuthenticatedDisciplinesRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFluxoDeAprovacaoRoute: typeof AuthenticatedFluxoDeAprovacaoRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedProjetistasRoute: typeof AuthenticatedProjetistasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisciplinesRoute: AuthenticatedDisciplinesRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFluxoDeAprovacaoRoute: AuthenticatedFluxoDeAprovacaoRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedProjetistasRoute: AuthenticatedProjetistasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
