/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrilhaDeAuditoriaRouteImport } from './routes/authenticated/trilha-de-auditoria'
import { Route as AuthenticatedProjetistasRouteImport } from './routes/authenticated/projetistas'
import { Route as AuthenticatedProjectsRouteImport } from './routes/authenticated/projects'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/authenticated/meu-perfil'
import { Route as AuthenticatedFluxoDeAprovacaoRouteImport } from './routes/authenticated/fluxo-de-aprovacao'
import { Route as AuthenticatedEquipeRouteImport } from './routes/authenticated/equipe'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/authenticated/documents'
import { Route as AuthenticatedDisciplinesRouteImport } from './routes/authenticated/disciplines'
import { Route as AuthenticatedDashboardRouteImport } from './routes/authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/authenticated/configuracoes'
import { Route as AuthenticatedDocumentsDocumentIdRouteImport } from './routes/authenticated/documents.$documentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrilhaDeAuditoriaRoute =
  AuthenticatedTrilhaDeAuditoriaRouteImport.update({
    id: '/trilha-de-auditoria',
    path: '/trilha-de-auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetistasRoute =
  AuthenticatedProjetistasRouteImport.update({
    id: '/projetistas',
    path: '/projetistas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluxoDeAprovacaoRoute =
  AuthenticatedFluxoDeAprovacaoRouteImport.update({
    id: '/fluxo-de-aprovacao',
    path: '/fluxo-de-aprovacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisciplinesRoute =
  AuthenticatedDisciplinesRouteImport.update({
    id: '/disciplines',
    path: '/disciplines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
  '/authenticated/trilha-de-auditoria': typeof AuthenticatedTrilhaDeAuditoriaRoute
  '/authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
  '/authenticated/trilha-de-auditoria': typeof AuthenticatedTrilhaDeAuditoriaRoute
  '/authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
  '/authenticated/trilha-de-auditoria': typeof AuthenticatedTrilhaDeAuditoriaRoute
  '/authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/login'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/meu-perfil'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
    | '/authenticated/trilha-de-auditoria'
    | '/authenticated/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/login'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/meu-perfil'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
    | '/authenticated/trilha-de-auditoria'
    | '/authenticated/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/authenticated'
    | '/auth'
    | '/login'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/meu-perfil'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
    | '/authenticated/trilha-de-auditoria'
    | '/authenticated/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/trilha-de-auditoria': {
      id: '/authenticated/trilha-de-auditoria'
      path: '/trilha-de-auditoria'
      fullPath: '/authenticated/trilha-de-auditoria'
      preLoaderRoute: typeof AuthenticatedTrilhaDeAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/projetistas': {
      id: '/authenticated/projetistas'
      path: '/projetistas'
      fullPath: '/authenticated/projetistas'
      preLoaderRoute: typeof AuthenticatedProjetistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/projects': {
      id: '/authenticated/projects'
      path: '/projects'
      fullPath: '/authenticated/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/meu-perfil': {
      id: '/authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/authenticated/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/fluxo-de-aprovacao': {
      id: '/authenticated/fluxo-de-aprovacao'
      path: '/fluxo-de-aprovacao'
      fullPath: '/authenticated/fluxo-de-aprovacao'
      preLoaderRoute: typeof AuthenticatedFluxoDeAprovacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/equipe': {
      id: '/authenticated/equipe'
      path: '/equipe'
      fullPath: '/authenticated/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/documents': {
      id: '/authenticated/documents'
      path: '/documents'
      fullPath: '/authenticated/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/disciplines': {
      id: '/authenticated/disciplines'
      path: '/disciplines'
      fullPath: '/authenticated/disciplines'
      preLoaderRoute: typeof AuthenticatedDisciplinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/dashboard': {
      id: '/authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/authenticated/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/configuracoes': {
      id: '/authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/authenticated/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/documents/$documentId': {
      id: '/authenticated/documents/$documentId'
      path: '/$documentId'
      fullPath: '/authenticated/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
  }
}

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsDocumentIdRoute:
      AuthenticatedDocumentsDocumentIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisciplinesRoute: typeof AuthenticatedDisciplinesRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFluxoDeAprovacaoRoute: typeof AuthenticatedFluxoDeAprovacaoRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedProjetistasRoute: typeof AuthenticatedProjetistasRoute
  AuthenticatedTrilhaDeAuditoriaRoute: typeof AuthenticatedTrilhaDeAuditoriaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisciplinesRoute: AuthenticatedDisciplinesRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFluxoDeAprovacaoRoute: AuthenticatedFluxoDeAprovacaoRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedProjetistasRoute: AuthenticatedProjetistasRoute,
  AuthenticatedTrilhaDeAuditoriaRoute: AuthenticatedTrilhaDeAuditoriaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
