/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrilhaDeAuditoriaRouteImport } from './routes/authenticated/trilha-de-auditoria'
import { Route as AuthenticatedSchemaDoctorRouteImport } from './routes/authenticated/schema-doctor'
import { Route as AuthenticatedProjetosRouteImport } from './routes/authenticated/projetos'
import { Route as AuthenticatedProjetistasRouteImport } from './routes/authenticated/projetistas'
import { Route as AuthenticatedProjectsRouteImport } from './routes/authenticated/projects'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/authenticated/meu-perfil'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/authenticated/indicadores'
import { Route as AuthenticatedGruposAprovacaoRouteImport } from './routes/authenticated/grupos-aprovacao'
import { Route as AuthenticatedFluxoDeAprovacaoRouteImport } from './routes/authenticated/fluxo-de-aprovacao'
import { Route as AuthenticatedEquipeRouteImport } from './routes/authenticated/equipe'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/authenticated/documents'
import { Route as AuthenticatedDisciplinesRouteImport } from './routes/authenticated/disciplines'
import { Route as AuthenticatedDashboardRouteImport } from './routes/authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/authenticated/configuracoes'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/authenticated/atividades'
import { Route as AuthenticatedDocumentsDocumentIdRouteImport } from './routes/authenticated/documents.$documentId'
import { Route as AuthenticatedDocumentosTramitesRouteImport } from './routes/authenticated/documentos/tramites'
import { Route as AuthenticatedDocumentosRegrasRouteImport } from './routes/authenticated/documentos/regras'
import { Route as AuthenticatedDocumentosNovoInteligenteRouteImport } from './routes/authenticated/documentos/novo-inteligente'
import { Route as AuthenticatedDocumentosCodificacaoRouteImport } from './routes/authenticated/documentos/codificacao'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrilhaDeAuditoriaRoute =
  AuthenticatedTrilhaDeAuditoriaRouteImport.update({
    id: '/trilha-de-auditoria',
    path: '/trilha-de-auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchemaDoctorRoute =
  AuthenticatedSchemaDoctorRouteImport.update({
    id: '/schema-doctor',
    path: '/schema-doctor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetistasRoute =
  AuthenticatedProjetistasRouteImport.update({
    id: '/projetistas',
    path: '/projetistas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGruposAprovacaoRoute =
  AuthenticatedGruposAprovacaoRouteImport.update({
    id: '/grupos-aprovacao',
    path: '/grupos-aprovacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFluxoDeAprovacaoRoute =
  AuthenticatedFluxoDeAprovacaoRouteImport.update({
    id: '/fluxo-de-aprovacao',
    path: '/fluxo-de-aprovacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisciplinesRoute =
  AuthenticatedDisciplinesRouteImport.update({
    id: '/disciplines',
    path: '/disciplines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedDocumentosTramitesRoute =
  AuthenticatedDocumentosTramitesRouteImport.update({
    id: '/documentos/tramites',
    path: '/documentos/tramites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosRegrasRoute =
  AuthenticatedDocumentosRegrasRouteImport.update({
    id: '/documentos/regras',
    path: '/documentos/regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosNovoInteligenteRoute =
  AuthenticatedDocumentosNovoInteligenteRouteImport.update({
    id: '/documentos/novo-inteligente',
    path: '/documentos/novo-inteligente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosCodificacaoRoute =
  AuthenticatedDocumentosCodificacaoRouteImport.update({
    id: '/documentos/codificacao',
    path: '/documentos/codificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/grupos-aprovacao': typeof AuthenticatedGruposAprovacaoRoute
  '/authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
  '/authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/authenticated/schema-doctor': typeof AuthenticatedSchemaDoctorRoute
  '/authenticated/trilha-de-auditoria': typeof AuthenticatedTrilhaDeAuditoriaRoute
  '/authenticated/documentos/codificacao': typeof AuthenticatedDocumentosCodificacaoRoute
  '/authenticated/documentos/novo-inteligente': typeof AuthenticatedDocumentosNovoInteligenteRoute
  '/authenticated/documentos/regras': typeof AuthenticatedDocumentosRegrasRoute
  '/authenticated/documentos/tramites': typeof AuthenticatedDocumentosTramitesRoute
  '/authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/grupos-aprovacao': typeof AuthenticatedGruposAprovacaoRoute
  '/authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
  '/authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/authenticated/schema-doctor': typeof AuthenticatedSchemaDoctorRoute
  '/authenticated/trilha-de-auditoria': typeof AuthenticatedTrilhaDeAuditoriaRoute
  '/authenticated/documentos/codificacao': typeof AuthenticatedDocumentosCodificacaoRoute
  '/authenticated/documentos/novo-inteligente': typeof AuthenticatedDocumentosNovoInteligenteRoute
  '/authenticated/documentos/regras': typeof AuthenticatedDocumentosRegrasRoute
  '/authenticated/documentos/tramites': typeof AuthenticatedDocumentosTramitesRoute
  '/authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/authenticated/disciplines': typeof AuthenticatedDisciplinesRoute
  '/authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/authenticated/fluxo-de-aprovacao': typeof AuthenticatedFluxoDeAprovacaoRoute
  '/authenticated/grupos-aprovacao': typeof AuthenticatedGruposAprovacaoRoute
  '/authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/authenticated/projects': typeof AuthenticatedProjectsRoute
  '/authenticated/projetistas': typeof AuthenticatedProjetistasRoute
  '/authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/authenticated/schema-doctor': typeof AuthenticatedSchemaDoctorRoute
  '/authenticated/trilha-de-auditoria': typeof AuthenticatedTrilhaDeAuditoriaRoute
  '/authenticated/documentos/codificacao': typeof AuthenticatedDocumentosCodificacaoRoute
  '/authenticated/documentos/novo-inteligente': typeof AuthenticatedDocumentosNovoInteligenteRoute
  '/authenticated/documentos/regras': typeof AuthenticatedDocumentosRegrasRoute
  '/authenticated/documentos/tramites': typeof AuthenticatedDocumentosTramitesRoute
  '/authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/login'
    | '/authenticated/atividades'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/grupos-aprovacao'
    | '/authenticated/indicadores'
    | '/authenticated/meu-perfil'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
    | '/authenticated/projetos'
    | '/authenticated/schema-doctor'
    | '/authenticated/trilha-de-auditoria'
    | '/authenticated/documentos/codificacao'
    | '/authenticated/documentos/novo-inteligente'
    | '/authenticated/documentos/regras'
    | '/authenticated/documentos/tramites'
    | '/authenticated/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/login'
    | '/authenticated/atividades'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/grupos-aprovacao'
    | '/authenticated/indicadores'
    | '/authenticated/meu-perfil'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
    | '/authenticated/projetos'
    | '/authenticated/schema-doctor'
    | '/authenticated/trilha-de-auditoria'
    | '/authenticated/documentos/codificacao'
    | '/authenticated/documentos/novo-inteligente'
    | '/authenticated/documentos/regras'
    | '/authenticated/documentos/tramites'
    | '/authenticated/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/authenticated'
    | '/auth'
    | '/login'
    | '/authenticated/atividades'
    | '/authenticated/configuracoes'
    | '/authenticated/dashboard'
    | '/authenticated/disciplines'
    | '/authenticated/documents'
    | '/authenticated/equipe'
    | '/authenticated/fluxo-de-aprovacao'
    | '/authenticated/grupos-aprovacao'
    | '/authenticated/indicadores'
    | '/authenticated/meu-perfil'
    | '/authenticated/projects'
    | '/authenticated/projetistas'
    | '/authenticated/projetos'
    | '/authenticated/schema-doctor'
    | '/authenticated/trilha-de-auditoria'
    | '/authenticated/documentos/codificacao'
    | '/authenticated/documentos/novo-inteligente'
    | '/authenticated/documentos/regras'
    | '/authenticated/documentos/tramites'
    | '/authenticated/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/trilha-de-auditoria': {
      id: '/authenticated/trilha-de-auditoria'
      path: '/trilha-de-auditoria'
      fullPath: '/authenticated/trilha-de-auditoria'
      preLoaderRoute: typeof AuthenticatedTrilhaDeAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/schema-doctor': {
      id: '/authenticated/schema-doctor'
      path: '/schema-doctor'
      fullPath: '/authenticated/schema-doctor'
      preLoaderRoute: typeof AuthenticatedSchemaDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/projetos': {
      id: '/authenticated/projetos'
      path: '/projetos'
      fullPath: '/authenticated/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/projetistas': {
      id: '/authenticated/projetistas'
      path: '/projetistas'
      fullPath: '/authenticated/projetistas'
      preLoaderRoute: typeof AuthenticatedProjetistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/projects': {
      id: '/authenticated/projects'
      path: '/projects'
      fullPath: '/authenticated/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/meu-perfil': {
      id: '/authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/authenticated/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/indicadores': {
      id: '/authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/authenticated/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/grupos-aprovacao': {
      id: '/authenticated/grupos-aprovacao'
      path: '/grupos-aprovacao'
      fullPath: '/authenticated/grupos-aprovacao'
      preLoaderRoute: typeof AuthenticatedGruposAprovacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/fluxo-de-aprovacao': {
      id: '/authenticated/fluxo-de-aprovacao'
      path: '/fluxo-de-aprovacao'
      fullPath: '/authenticated/fluxo-de-aprovacao'
      preLoaderRoute: typeof AuthenticatedFluxoDeAprovacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/equipe': {
      id: '/authenticated/equipe'
      path: '/equipe'
      fullPath: '/authenticated/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/documents': {
      id: '/authenticated/documents'
      path: '/documents'
      fullPath: '/authenticated/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/disciplines': {
      id: '/authenticated/disciplines'
      path: '/disciplines'
      fullPath: '/authenticated/disciplines'
      preLoaderRoute: typeof AuthenticatedDisciplinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/dashboard': {
      id: '/authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/authenticated/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/configuracoes': {
      id: '/authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/authenticated/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/atividades': {
      id: '/authenticated/atividades'
      path: '/atividades'
      fullPath: '/authenticated/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/documents/$documentId': {
      id: '/authenticated/documents/$documentId'
      path: '/$documentId'
      fullPath: '/authenticated/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/authenticated/documentos/tramites': {
      id: '/authenticated/documentos/tramites'
      path: '/documentos/tramites'
      fullPath: '/authenticated/documentos/tramites'
      preLoaderRoute: typeof AuthenticatedDocumentosTramitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/documentos/regras': {
      id: '/authenticated/documentos/regras'
      path: '/documentos/regras'
      fullPath: '/authenticated/documentos/regras'
      preLoaderRoute: typeof AuthenticatedDocumentosRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/documentos/novo-inteligente': {
      id: '/authenticated/documentos/novo-inteligente'
      path: '/documentos/novo-inteligente'
      fullPath: '/authenticated/documentos/novo-inteligente'
      preLoaderRoute: typeof AuthenticatedDocumentosNovoInteligenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/documentos/codificacao': {
      id: '/authenticated/documentos/codificacao'
      path: '/documentos/codificacao'
      fullPath: '/authenticated/documentos/codificacao'
      preLoaderRoute: typeof AuthenticatedDocumentosCodificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsDocumentIdRoute:
      AuthenticatedDocumentsDocumentIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisciplinesRoute: typeof AuthenticatedDisciplinesRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFluxoDeAprovacaoRoute: typeof AuthenticatedFluxoDeAprovacaoRoute
  AuthenticatedGruposAprovacaoRoute: typeof AuthenticatedGruposAprovacaoRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedProjetistasRoute: typeof AuthenticatedProjetistasRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedSchemaDoctorRoute: typeof AuthenticatedSchemaDoctorRoute
  AuthenticatedTrilhaDeAuditoriaRoute: typeof AuthenticatedTrilhaDeAuditoriaRoute
  AuthenticatedDocumentosCodificacaoRoute: typeof AuthenticatedDocumentosCodificacaoRoute
  AuthenticatedDocumentosNovoInteligenteRoute: typeof AuthenticatedDocumentosNovoInteligenteRoute
  AuthenticatedDocumentosRegrasRoute: typeof AuthenticatedDocumentosRegrasRoute
  AuthenticatedDocumentosTramitesRoute: typeof AuthenticatedDocumentosTramitesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisciplinesRoute: AuthenticatedDisciplinesRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFluxoDeAprovacaoRoute: AuthenticatedFluxoDeAprovacaoRoute,
  AuthenticatedGruposAprovacaoRoute: AuthenticatedGruposAprovacaoRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedProjetistasRoute: AuthenticatedProjetistasRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedSchemaDoctorRoute: AuthenticatedSchemaDoctorRoute,
  AuthenticatedTrilhaDeAuditoriaRoute: AuthenticatedTrilhaDeAuditoriaRoute,
  AuthenticatedDocumentosCodificacaoRoute:
    AuthenticatedDocumentosCodificacaoRoute,
  AuthenticatedDocumentosNovoInteligenteRoute:
    AuthenticatedDocumentosNovoInteligenteRoute,
  AuthenticatedDocumentosRegrasRoute: AuthenticatedDocumentosRegrasRoute,
  AuthenticatedDocumentosTramitesRoute: AuthenticatedDocumentosTramitesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
